# Generated by Django 5.1.15 on 2026-06-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['nom', 'prenom'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id_destination', models.IntegerField(primary_key=True, serialize=False)),
                ('pays', models.CharField(max_length=80)),
                ('ville', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('prix_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'destinations',
                'ordering': ['pays', 'ville'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.IntegerField(primary_key=True, serialize=False)),
                ('id_client', models.IntegerField()),
                ('id_voyage', models.IntegerField()),
                ('date_reservation', models.DateField()),
                ('nombre_personnes', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='EN ATTENTE', max_length=20)),
            ],
            options={
                'db_table': 'reservations',
                'ordering': ['-date_reservation'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id_voyage', models.IntegerField(primary_key=True, serialize=False)),
                ('id_destination', models.IntegerField()),
                ('date_depart', models.DateField()),
                ('date_retour', models.DateField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('places_disponibles', models.IntegerField()),
            ],
            options={
                'db_table': 'voyages',
                'ordering': ['date_depart'],
                'managed': False,
            },
        ),
    ]
